apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-4x0n9d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-4x0n9d
  namespace: my-nginx-4x0n9d
  labels:
    name: nginx-4x0n9d
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-4x0n9d
  template:
    metadata:
      namespace: my-nginx-4x0n9d
      labels:
        name: nginx-4x0n9d
    spec:
      containers:
      - name: nginx-4x0n9d
        image: nginx
        ports:
        - containerPort: 80

